# Generated by Django 6.0.6 on 2026-06-09 01:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Annonce',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('offre', 'Je propose du mentorat'), ('demande', 'Je cherche du mentorat')], default='offre', max_length=10)),
                ('matieres', models.JSONField(blank=True, default=list)),
                ('description', models.TextField(blank=True, default='')),
                ('format', models.CharField(choices=[('presentiel', 'Présentiel'), ('en_ligne', 'En ligne'), ('les_deux', 'Les deux')], default='presentiel', max_length=10)),
                ('disponibilites', models.JSONField(blank=True, default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('auteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='annonces', to='accounts.etudiant')),
            ],
            options={
                'verbose_name': 'Annonce',
                'verbose_name_plural': 'Annonces',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(default=0)),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('accepte', 'Accepté'), ('refuse', 'Refusé')], default='en_attente', max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mentor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matchs_en_tant_que_mentor', to='accounts.etudiant')),
                ('mentore', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matchs_en_tant_que_mentore', to='accounts.etudiant')),
            ],
            options={
                'verbose_name': 'Match',
                'verbose_name_plural': 'Matchs',
                'ordering': ['-score'],
                'unique_together': {('mentor', 'mentore')},
            },
        ),
    ]
