# Generated by Django 6.0.6 on 2026-06-09 01:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Etudiant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telephone', models.CharField(blank=True, default='', max_length=20)),
                ('avatar', models.URLField(blank=True, default='', max_length=500)),
                ('bio', models.TextField(blank=True, default='')),
                ('location', models.CharField(blank=True, default='Abomey-Calavi, Bénin', max_length=100)),
                ('filiere', models.CharField(choices=[('GL', 'Génie Logiciel'), ('IA', 'Intelligence Artificielle'), ('SI', 'Sécurité Informatique'), ('SE', 'Systèmes Embarqués & IoT'), ('IM', 'Internet et Multimédia')], default='GL', max_length=2)),
                ('niveau', models.CharField(choices=[('L1', 'Licence 1'), ('L2', 'Licence 2'), ('L3', 'Licence 3'), ('M1', 'Master 1'), ('M2', 'Master 2')], default='L1', max_length=2)),
                ('points_forts', models.JSONField(blank=True, default=list)),
                ('points_faibles', models.JSONField(blank=True, default=list)),
                ('disponibilites', models.JSONField(blank=True, default=list)),
                ('is_mentor', models.BooleanField(default=False)),
                ('is_online', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='etudiant', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Étudiant',
                'verbose_name_plural': 'Étudiants',
                'ordering': ['-created_at'],
            },
        ),
    ]
