# Generated by Django 6.0.6 on 2026-06-09 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_etudiant_sexe'),
    ]

    operations = [
        migrations.AddField(
            model_name='etudiant',
            name='photo_couverture',
            field=models.ImageField(blank=True, null=True, upload_to='profils/couvertures/'),
        ),
        migrations.AddField(
            model_name='etudiant',
            name='photo_profil',
            field=models.ImageField(blank=True, null=True, upload_to='profils/avatars/'),
        ),
    ]
